version: '3'

services:
    notebook:
        image: hellospencer/jupyterspark23
        ports:
            - ${JUPYTERPORT}:8888
            - 8080:8080
            - 8081:8081 
            - 7077:7077
        volumes:
            - ${NOTEBOOKDIR}:${NOTEBOOKROOT}
            - ${OTHERNOTEBOOK}:${NOTEBOOKROOT}/other 
            - ${DATADIR}:/home/jupyter/notebooks/Data


