version: '3'

services:
    notebook:
        image: blackplane/jupyterspark23
        ports:
            - ${JUPYTERPORT}:8888
            - 8080:8080
            - 8081:8081 
            - 7077:7077
        volumes:
            - ${NOTEBOOKDIR}:${NOTEBOOKROOT}
            - ${OTHERNOTEBOOK}:${NOTEBOOKROOT}/other 
            - ${DATADIR}:/home/jupyter/notebooks/Data
            - /Users/armin.wasicek/Documents/aut-taxes_2017:${NOTEBOOKROOT}/aut-taxes_2017
            - /Users/armin.wasicek/Documents/aut-taxes_2018:${NOTEBOOKROOT}/aut-taxes_2018
        


