version: '3'

services:
    notebook:
        image: blackplane/jupyterspark23
        ports:
            - ${JUPYTERPORT}:8888
            - 8080:8080
            - 8081:8081 
            - 7077:7077
        volumes:
            - ${NOTEBOOKDIR}:${NOTEBOOKROOT}
            - ${DATADIR}:/home/jupyter/notebooks/Data
            - ${CRYPTONOTEBOOK}:${NOTEBOOKROOT}/crypto
            - ${SYNIDNOTEBOOK}:${NOTEBOOKROOT}/synid
        


